services:
  - type: web
    name: jidelna-pwa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JIDELNA_LOGIN
        sync: false
      - key: JIDELNA_HESLO
        sync: false
      - key: GEMINI_API_KEY
        sync: false

